// Code generated by "stringer -type=EntityStatus -linecomment"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EntityStatusOk-1]
	_ = x[EntityStatusBorrowed-2]
	_ = x[EntityStatusMissing-3]
	_ = x[EntityStatusLoaned-4]
	_ = x[EntityStatusRemoved-5]
}

const _EntityStatus_name = "okborrowedmissingloanedremoved"

var _EntityStatus_index = [...]uint8{0, 2, 10, 17, 23, 30}

func (i EntityStatus) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_EntityStatus_index)-1 {
		return "EntityStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntityStatus_name[_EntityStatus_index[idx]:_EntityStatus_index[idx+1]]
}
