// Code generated by "stringer -type=EntityType -linecomment"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EntityTypePlace-1]
	_ = x[EntityTypeContainer-2]
	_ = x[EntityTypeLeaf-3]
}

const _EntityType_name = "placecontainerleaf"

var _EntityType_index = [...]uint8{0, 5, 14, 18}

func (i EntityType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_EntityType_index)-1 {
		return "EntityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntityType_name[_EntityType_index[idx]:_EntityType_index[idx+1]]
}
