// Code generated by "stringer -type=EventType -linecomment"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemCreatedEvent-1]
	_ = x[ItemMovedEvent-2]
	_ = x[ItemMissingEvent-3]
	_ = x[ItemBorrowedEvent-4]
	_ = x[ItemLoanedEvent-5]
	_ = x[ItemFoundEvent-6]
	_ = x[ItemRemovedEvent-7]
	_ = x[LocationCreatedEvent-8]
	_ = x[LocationRenamedEvent-9]
	_ = x[LocationMovedEvent-10]
	_ = x[LocationRemovedEvent-11]
}

const _EventType_name = "item.createditem.moveditem.missingitem.borroweditem.loaneditem.founditem.removedlocation.createdlocation.renamedlocation.reparentedlocation.removed"

var _EventType_index = [...]uint8{0, 12, 22, 34, 47, 58, 68, 80, 96, 112, 131, 147}

func (i EventType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_EventType_index)-1 {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[idx]:_EventType_index[idx+1]]
}
