with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | lower}}.go"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/asphaltbuffet/wherehouse/internal/logging:
    interfaces:
      Logger:
  github.com/asphaltbuffet/wherehouse/cmd/move:
    interfaces:
      moveDB:
