dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceName | lower}}.go"
log-level: warn
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/asphaltbuffet/wherehouse/cmd/add:
    interfaces:
      addDB: {}
  github.com/asphaltbuffet/wherehouse/internal/logging:
    interfaces:
      Logger: {}
