schema = 3

[mod]
  [mod."charm.land/lipgloss/v2"]
    version = "v2.0.0-beta.3.0.20251106193318-19329a3e8410"
    hash = "sha256-iLsJGqxaSpBKMpM+K8oA7OKUydjBAdDl80Y3Xnf1xVA="
  [mod."github.com/agnivade/levenshtein"]
    version = "v1.2.1"
    hash = "sha256-3XnCzf7tFgEE0MmjxvjfWaw6qK6mKLabFZ3c23JIH9Y="
  [mod."github.com/araddon/dateparse"]
    version = "v0.0.0-20210429162001-6b43995a97de"
    hash = "sha256-UuX84naeRGMsFOgIgRoBHG5sNy1CzBkWPKmd6VbLwFw="
  [mod."github.com/charmbracelet/colorprofile"]
    version = "v0.3.3"
    hash = "sha256-OIbahp2GyekOAHw7RB7/4WEOEjqpP/PqK6wfIq1iSkk="
  [mod."github.com/charmbracelet/fang"]
    version = "v0.4.4"
    hash = "sha256-KnwAd/LVJC5gxO/xT80NduudQqA8JNnoDRFE77k30qs="
  [mod."github.com/charmbracelet/ultraviolet"]
    version = "v0.0.0-20251106190538-99ea45596692"
    hash = "sha256-dKNaSNSluFa250SfCOUKzSJ8WfBg03O9azcvhTq4qMM="
  [mod."github.com/charmbracelet/x/ansi"]
    version = "v0.11.0"
    hash = "sha256-P3jCKqEem/gW8dUWiol7K1cZe1Zr2UE2jNe9j884+nk="
  [mod."github.com/charmbracelet/x/exp/charmtone"]
    version = "v0.0.0-20250603201427-c31516f43444"
    hash = "sha256-x6EfMobGGF31tnkjXuoGLxAa6V1ozsR2Z43TQu9/mX0="
  [mod."github.com/charmbracelet/x/term"]
    version = "v0.2.2"
    hash = "sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4="
  [mod."github.com/charmbracelet/x/termios"]
    version = "v0.1.1"
    hash = "sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds="
  [mod."github.com/charmbracelet/x/windows"]
    version = "v0.2.2"
    hash = "sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk="
  [mod."github.com/clipperhouse/displaywidth"]
    version = "v0.4.1"
    hash = "sha256-Cchc3GXYSn4eVbsY4DdqeCL0KAh1mYS/mMQnAzeVSBw="
  [mod."github.com/clipperhouse/stringish"]
    version = "v0.1.1"
    hash = "sha256-Mp8M1CRbwr6dcJ4BD9tXD5I78ZgCFEm0GDxJv0GYReg="
  [mod."github.com/clipperhouse/uax29/v2"]
    version = "v2.3.0"
    hash = "sha256-dLL70mEOxrmYVoQjy2K7QvZiahAlJKOcFDz2mW/R/Do="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.9.0"
    hash = "sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g="
  [mod."github.com/go-viper/mapstructure/v2"]
    version = "v2.4.0"
    hash = "sha256-lLfcV9z4n94hDhgyXJlde4bFB0hfzlbh+polqcJCwGE="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.5"
    hash = "sha256-/EtlGihP0/7oInzMC5E0InZ4b5Ad3s4xOpqotloi3xw="
  [mod."github.com/golang-migrate/migrate/v4"]
    version = "v4.19.1"
    hash = "sha256-J3htVA6mxGWNik3WPWuulnnhcP0vz2n+oQOgAAO0R3U="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.3.0"
    hash = "sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.19"
    hash = "sha256-GpnbKplhX410Q/eIdknvWbYZgdav1keN+7wNUeOSMHE="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/mango"]
    version = "v0.1.0"
    hash = "sha256-Xy63UxeZJMU4JlG6uuEpUeyxTGytx+NDbqCAgXpZrrU="
  [mod."github.com/muesli/mango-cobra"]
    version = "v1.2.0"
    hash = "sha256-26X9H9t2Z/kLII2n/Zd+D568H2rlbVJPS11jT25bdUA="
  [mod."github.com/muesli/mango-pflag"]
    version = "v0.1.0"
    hash = "sha256-qgUxVjVFmbcGjn8m58DRRu4hmYhirEUDy9TjkJYU8m4="
  [mod."github.com/muesli/roff"]
    version = "v0.1.0"
    hash = "sha256-0A/M8h0+dSF1NruiGjs4WbfWENFbV3VpyIwJzHEeRlA="
  [mod."github.com/ncruces/go-strftime"]
    version = "v1.0.0"
    hash = "sha256-GYIwYDONuv/yTE0AEugCHQbtV3oiBaco93xUNYFcVBQ="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.4"
    hash = "sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20230129092748-24d4a6f8daec"
    hash = "sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.11.0"
    hash = "sha256-PUX8dzJtkD8YDZFNqpHnl4qgb0tE1W/DLnL7V+/d1z4="
  [mod."github.com/sourcegraph/conc"]
    version = "v0.3.1-0.20240121214520-5f936abd7ae8"
    hash = "sha256-AUNFlY6K7s1aoW/vb4pjK84ROdnVZY1i6cOmdeG+wN8="
  [mod."github.com/spf13/afero"]
    version = "v1.15.0"
    hash = "sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8="
  [mod."github.com/spf13/cast"]
    version = "v1.10.0"
    hash = "sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/spf13/viper"]
    version = "v1.21.0"
    hash = "sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."github.com/xo/terminfo"]
    version = "v0.0.0-20220910002029-abceb7e1c41e"
    hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20251023183803-a4bb9ffd2546"
    hash = "sha256-y0/A9UdtYNDlFglHQ7TW8ixSR2G36wHMRNc3sL7JXBY="
  [mod."golang.org/x/sync"]
    version = "v0.18.0"
    hash = "sha256-S8o6y7GOaYWeq+TzT8BB6T+1mg82Mu08V0TL3ukJprg="
  [mod."golang.org/x/sys"]
    version = "v0.38.0"
    hash = "sha256-1+i5EaG3JwH3KMtefzJLG5R6jbOeJM4GK3/LHBVnSy0="
  [mod."golang.org/x/text"]
    version = "v0.31.0"
    hash = "sha256-AT46RrSmV6+/d5FDhs9fPwYzmQ7WSo+YL9tPfhREwLw="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.2.1"
    hash = "sha256-GaXWRDxhGy4Z4mgE+bJ8OE9SVvYUa9TnNiydnp2s1Ms="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."modernc.org/libc"]
    version = "v1.67.6"
    hash = "sha256-AmcruJSR6Rd6ORFKTm+xSB6G9aqW2dAw/+mWsG2FwcU="
  [mod."modernc.org/mathutil"]
    version = "v1.7.1"
    hash = "sha256-COZ5rF2GhQVR1r6a0DanJ8qwQ94JSKdQxTMWrDzE0Cc="
  [mod."modernc.org/memory"]
    version = "v1.11.0"
    hash = "sha256-MkybF8vvrxXS5j7O8w3skwTo0aMo1yjWS0K440rYcHM="
  [mod."modernc.org/sqlite"]
    version = "v1.46.1"
    hash = "sha256-9LNxkEmstJOY4GUCzbDxCkBitHH+ZH7jmKz8xlCGmNE="
