schema = 3

[mod]
  [mod."charm.land/lipgloss/v2"]
    version = "v2.0.0"
    hash = "sha256-O78AzqA19r2N7DpRwj7pCk57Spqo8FkdD1J8frGQqoc="
  [mod."github.com/agnivade/levenshtein"]
    version = "v1.2.1"
    hash = "sha256-3XnCzf7tFgEE0MmjxvjfWaw6qK6mKLabFZ3c23JIH9Y="
  [mod."github.com/araddon/dateparse"]
    version = "v0.0.0-20210429162001-6b43995a97de"
    hash = "sha256-UuX84naeRGMsFOgIgRoBHG5sNy1CzBkWPKmd6VbLwFw="
  [mod."github.com/charmbracelet/colorprofile"]
    version = "v0.4.2"
    hash = "sha256-AMnmwWjpv/TMb2mbqVXB4RmMVWBsrTFlq1FL8A00olw="
  [mod."github.com/charmbracelet/fang"]
    version = "v0.4.4"
    hash = "sha256-KnwAd/LVJC5gxO/xT80NduudQqA8JNnoDRFE77k30qs="
  [mod."github.com/charmbracelet/ultraviolet"]
    version = "v0.0.0-20260223171050-89c142e4aa73"
    hash = "sha256-SAwYzKlL9LqaTLZw60823FiZPOyYDRrqBws5ZVUj4Os="
  [mod."github.com/charmbracelet/x/ansi"]
    version = "v0.11.6"
    hash = "sha256-UToZIkqXl9MEppcRgbeBqaaMeAzRkGa0w3lVUs6sxWI="
  [mod."github.com/charmbracelet/x/exp/charmtone"]
    version = "v0.0.0-20260301003739-baafbde16d0a"
    hash = "sha256-Q6ouXSvCucqKj3S7J0r7lyxQ1NpiuF80mgkmgnvtvMw="
  [mod."github.com/charmbracelet/x/term"]
    version = "v0.2.2"
    hash = "sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4="
  [mod."github.com/charmbracelet/x/termios"]
    version = "v0.1.1"
    hash = "sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds="
  [mod."github.com/charmbracelet/x/windows"]
    version = "v0.2.2"
    hash = "sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk="
  [mod."github.com/clipperhouse/displaywidth"]
    version = "v0.11.0"
    hash = "sha256-WokyTaofEy95xlshqK5YDzpemhXV5oaQifxS9YyfCXo="
  [mod."github.com/clipperhouse/uax29/v2"]
    version = "v2.7.0"
    hash = "sha256-GO3az7WiGcwU0OvmocwdfR5ohGRL8NbjscIaMyhAdxE="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.9.0"
    hash = "sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g="
  [mod."github.com/go-viper/mapstructure/v2"]
    version = "v2.5.0"
    hash = "sha256-LbrCBANBprVI84M0CWrXc7rriJL5ac5VKbh58LBTw7U="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.5"
    hash = "sha256-/EtlGihP0/7oInzMC5E0InZ4b5Ad3s4xOpqotloi3xw="
  [mod."github.com/golang-migrate/migrate/v4"]
    version = "v4.19.1"
    hash = "sha256-J3htVA6mxGWNik3WPWuulnnhcP0vz2n+oQOgAAO0R3U="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.3.0"
    hash = "sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU="
  [mod."github.com/matoous/go-nanoid/v2"]
    version = "v2.1.0"
    hash = "sha256-SapI0yn7X8Ao2QOfrT1dZu67qFSLd/jqxDfk3yiYWOI="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.20"
    hash = "sha256-Y3qYfCqPt+Ce/MEk8dr6pSdd1ZwO2Nwm5sjLIbw26TY="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/mango"]
    version = "v0.2.0"
    hash = "sha256-hEu9ZE2yYBCD2O9KNq8Lgc8dGeCPrTgx/b0tZtTToJk="
  [mod."github.com/muesli/mango-cobra"]
    version = "v1.3.0"
    hash = "sha256-VPE2A9eyMI63789PcnM5Ltm5PWt/yewWVh7hKtyoe4c="
  [mod."github.com/muesli/mango-pflag"]
    version = "v0.2.0"
    hash = "sha256-gF9oIQpH9iGFEzDOrfgurtVOd1BjGmSRMkNDnSJClcw="
  [mod."github.com/muesli/roff"]
    version = "v0.1.0"
    hash = "sha256-0A/M8h0+dSF1NruiGjs4WbfWENFbV3VpyIwJzHEeRlA="
  [mod."github.com/ncruces/go-strftime"]
    version = "v1.0.0"
    hash = "sha256-GYIwYDONuv/yTE0AEugCHQbtV3oiBaco93xUNYFcVBQ="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.4"
    hash = "sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20230129092748-24d4a6f8daec"
    hash = "sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.12.0"
    hash = "sha256-EXk9S5Z5sYyApAzCgHIugsGMbt/pHWRfHYFZH5D+5Ws="
  [mod."github.com/spf13/afero"]
    version = "v1.15.0"
    hash = "sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8="
  [mod."github.com/spf13/cast"]
    version = "v1.10.0"
    hash = "sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/spf13/viper"]
    version = "v1.21.0"
    hash = "sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."github.com/xlab/treeprint"]
    version = "v1.2.0"
    hash = "sha256-g85HyWGLZuD/TFXZzmXT+u9TA1xIT5escUVhnofsYQI="
  [mod."github.com/xo/terminfo"]
    version = "v0.0.0-20220910002029-abceb7e1c41e"
    hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20260218203240-3dfff04db8fa"
    hash = "sha256-vsit1x+iQymfiWhINdZgd4wQhMoWMp3tqcjbDjcV0oY="
  [mod."golang.org/x/sync"]
    version = "v0.19.0"
    hash = "sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno="
  [mod."golang.org/x/sys"]
    version = "v0.41.0"
    hash = "sha256-owjs3/IzAKfFlIz1U1fiHSfl2+bTUhaXTyWEjL5SWHk="
  [mod."golang.org/x/text"]
    version = "v0.34.0"
    hash = "sha256-wGKd1JkeiFROibvo2kkAuQ7JajSIfV4utGaoGbTQhQM="
  [mod."golang.org/x/tools"]
    version = "v0.42.0"
    hash = "sha256-JTwzoJeqCW5aphjQR0SItRGov7dKVbFk3a4V2U2+vd4="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20190902080502-41f04d3bba15"
    hash = "sha256-Xl5gjoqU26M+Yxm6Xok5VHVpYT5hItwsN7d2Wj9L020="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.2.1"
    hash = "sha256-GaXWRDxhGy4Z4mgE+bJ8OE9SVvYUa9TnNiydnp2s1Ms="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."modernc.org/libc"]
    version = "v1.68.1"
    hash = "sha256-k1gnRoSBAIhwsfDoxj0LM42vDCnmP3WxzjkeLBktSqs="
  [mod."modernc.org/mathutil"]
    version = "v1.7.1"
    hash = "sha256-COZ5rF2GhQVR1r6a0DanJ8qwQ94JSKdQxTMWrDzE0Cc="
  [mod."modernc.org/memory"]
    version = "v1.11.0"
    hash = "sha256-MkybF8vvrxXS5j7O8w3skwTo0aMo1yjWS0K440rYcHM="
  [mod."modernc.org/sqlite"]
    version = "v1.46.1"
    hash = "sha256-9LNxkEmstJOY4GUCzbDxCkBitHH+ZH7jmKz8xlCGmNE="
