// Code generated by "stringer -type=DoctorKind -linecomment"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DoctorKindConfig-1]
	_ = x[DoctorKindEventLog-2]
	_ = x[DoctorKindProjection-3]
}

const _DoctorKind_name = "configevent_logprojection"

var _DoctorKind_index = [...]uint8{0, 6, 15, 25}

func (i DoctorKind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_DoctorKind_index)-1 {
		return "DoctorKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DoctorKind_name[_DoctorKind_index[idx]:_DoctorKind_index[idx+1]]
}
