// Code generated by "stringer -type=EventType -linecomment"; DO NOT EDIT.

package inventory

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EntityCreatedEvent-1]
	_ = x[EntityRenamedEvent-2]
	_ = x[EntityReparentedEvent-3]
	_ = x[EntityPathChangedEvent-4]
	_ = x[EntityStatusChangedEvent-5]
	_ = x[EntityRemovedEvent-6]
	_ = x[EntityTagAddedEvent-7]
	_ = x[EntityTagRemovedEvent-8]
	_ = x[EntityLockedEvent-9]
	_ = x[EntityUnlockedEvent-10]
	_ = x[EntityDiscreteSetEvent-11]
	_ = x[EntityDiscreteClearedEvent-12]
}

const _EventType_name = "entity.createdentity.renamedentity.reparentedentity.path_changedentity.status_changedentity.removedentity.tag_addedentity.tag_removedentity.lockedentity.unlockedentity.discrete_setentity.discrete_cleared"

var _EventType_index = [...]uint8{0, 14, 28, 45, 64, 85, 99, 115, 133, 146, 161, 180, 203}

func (i EventType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_EventType_index)-1 {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[idx]:_EventType_index[idx+1]]
}
