# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Main Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  govulncheck:
    uses: asphaltbuffet/.github/.github/workflows/vulncheck.yml@main
  test:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Build
        run: mise run ci

      - name: Archive code coverage results
        uses: actions/upload-artifact@v6
        with:
          name: code-coverage-report-${{ matrix.os }}
          path: bin

      - name: Upload code coverage results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./bin/coverage.out
          flags: ${{ runner.os }}

  snapshot:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Set up mise
        uses: jdx/mise-action@v3

      - uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Release Test
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: "~> v2"
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
